projects:
  ServiceWRKPortal:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-south-1
        apiId: 447j2v5bzjaureqoxwla7glwhe
        maxDepth: 7
extensions:
  amplify:
    version: 3
