<template>
  <div>
    <v-dialog v-model="PayoutInfoDialog" persistent max-width="900px">
      <v-card>
        <v-toolbar dark dense class="elevation-0" color="primary">
          <div>Payout Info</div>
          <v-spacer></v-spacer>
          <v-btn icon @click="PayoutInfoDialogEmit(1)">
            <v-icon>mdi-close</v-icon>
          </v-btn>
        </v-toolbar>
        <v-card-text>
          <v-tabs v-model="Tabmodel" slider-color="primary" class="mb-3">
            <v-tab class="text-capitalize"
              >Invoice Info{{
                PayoutObj.payment_details ? " & Updated Payment Info" : ""
              }}</v-tab
            >
            <v-tab class="text-capitalize">History</v-tab>
            <v-spacer />
          </v-tabs>
          <v-tabs-items v-model="Tabmodel">
            <v-tab-item>
              <div>
                <div
                  style="border: 1px solid black; border-style: dashed"
                  class="pa-5"
                >
                  <h3>Invoice Info</h3>
                  <v-row align="center">
                    <v-col cols="12" lg="6">
                      <div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Display ID: </strong
                            >{{ PayoutObj.invoice_display_id || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Generated By Email: </strong
                            >{{
                              PayoutObj.invoice_generated_by_email || "N/A"
                            }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Generated On: </strong
                            >{{
                              new Date(
                                PayoutObj.invoice_generated_on * 1000
                              ).toLocaleString("en-GB") || "N/A"
                            }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Modified On: </strong
                            >{{
                              new Date(
                                PayoutObj.invoice_modified_on * 1000
                              ).toLocaleString("en-GB") || "N/A"
                            }}
                          </span>
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Month: </strong
                            >{{ PayoutObj.invoice_month || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Payment Initiated On: </strong
                            >{{
                              new Date(
                                PayoutObj.is_payment_initiated_on * 1000
                              ).toLocaleString("en-GB") || "N/A"
                            }}
                          </span>
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Reporting User Name: </strong
                            >{{ PayoutObj.reporting_user_name || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Reporting User Email: </strong
                            >{{
                              PayoutObj.reporting_user_email_id || "N/A"
                            }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Total Cost: </strong
                            >{{ PayoutObj.total_cost || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice PDF: </strong>
                            <v-btn
                              icon
                              v-if="PayoutObj.invoice_s3_url"
                              @click="viewPDFMethod(PayoutObj.invoice_s3_url)"
                              ><v-icon color="primary" small class="pl-1"
                                >mdi-paperclip</v-icon
                              ></v-btn
                            >
                            <span v-else>-</span>
                          </span>
                        </div>
                      </div>
                    </v-col>
                    <v-col cols="12" lg="6">
                      <div>
                        <div>
                          <span class="FontSize"
                            ><strong>Payment Invoice Display ID: </strong
                            >{{
                              PayoutObj.payment_invoice_display_id || "N/A"
                            }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Payment Month: </strong
                            >{{ PayoutObj.payment_month || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Payment Workflow Initiated On: </strong>
                            {{
                              new Date(
                                PayoutObj.payment_workflow_initiated_on * 1000
                              ).toLocaleString("en-GB") || "N/A"
                            }}
                          </span>
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Payment Workflow Modified On: </strong>
                            {{
                              new Date(
                                PayoutObj.payment_workflow_modified_on * 1000
                              ).toLocaleString("en-GB") || "N/A"
                            }}
                            }</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Pending At: </strong
                            >{{ PayoutObj.pending_at || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Display ID: </strong
                            >{{ PayoutObj.invoice_display_id || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Generated By Name: </strong
                            >{{
                              PayoutObj.invoice_generated_by_name || "N/A"
                            }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Generated By Email: </strong
                            >{{
                              PayoutObj.invoice_generated_by_email || "N/A"
                            }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Initiated On: </strong
                            >{{
                              new Date(
                                PayoutObj.invoice_initiated_on * 1000
                              ).toLocaleString("en-GB") || "N/A"
                            }}
                          </span>
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Invoice Month: </strong
                            >{{ PayoutObj.invoice_month || "N/A" }}</span
                          >
                        </div>
                        <div>
                          <span class="FontSize"
                            ><strong>Payment PDF: </strong>
                            <v-btn
                              icon
                              v-if="
                                PayoutObj.payment_workflow_initiated_attachments &&
                                PayoutObj.payment_workflow_initiated_attachments
                                  .length > 0
                              "
                              @click="
                                viewPDFMethod(
                                  PayoutObj
                                    .payment_workflow_initiated_attachments[0]
                                    .file_url
                                )
                              "
                              ><v-icon color="primary" small class="pl-1"
                                >mdi-paperclip</v-icon
                              ></v-btn
                            >
                            <span v-else>-</span>
                          </span>
                        </div>
                      </div>
                    </v-col>
                  </v-row>
                </div>
                <div
                  class="mt-3 pa-5"
                  v-if="PayoutObj.payment_details"
                  style="border: 1px solid black; border-style: dashed"
                >
                  <h3>Updated Payment Info</h3>
                  <div class="mt-2">
                    <span class="FontSize"
                      ><strong>Date of Payment: </strong
                      >{{
                        PayoutObj.payment_details?.date_of_payment || "N/A"
                      }}</span
                    >
                  </div>
                  <div>
                    <span class="FontSize"
                      ><strong>Mode of Payment: </strong
                      >{{
                        PayoutObj.payment_details?.mode_of_payment || "N/A"
                      }}</span
                    >
                  </div>
                  <div>
                    <span class="FontSize"
                      ><strong>Payment Reference Number: </strong
                      >{{
                        PayoutObj.payment_details?.payment_reference_number ||
                        "N/A"
                      }}</span
                    >
                  </div>
                  <div>
                    <span class="FontSize"
                      ><strong>Payment Type: </strong
                      >{{
                        PayoutObj.payment_details?.payment_type || "N/A"
                      }}</span
                    >
                  </div>
                  <div>
                    <span class="FontSize"
                      ><strong>Payment Value: </strong
                      >{{
                        PayoutObj.payment_details?.payment_value || "N/A"
                      }}</span
                    >
                  </div>
                </div>
              </div>
            </v-tab-item>
            <v-tab-item>
              <div
                style="display: flex; flex-direction: column"
                class="pt-3"
                v-if="PayoutObj.invoiceOrPayment === 'INVOICE'"
              >
                <v-card
                  color="#f3e5f5"
                  v-for="(item, index) in PayoutObj.invoice_history"
                  :key="index"
                  class="pa-5 mb-4"
                >
                  <div>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Action Taken By: </strong
                        >{{ item.action_taken_by }}</span
                      >
                    </p>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Action Time: </strong
                        >{{ item.action_time }}</span
                      >
                    </p>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Action Type: </strong
                        >{{ item.action_type }}</span
                      >
                    </p>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Email ID: </strong
                        >{{ item.user_contact }}</span
                      >
                    </p>
                  </div>
                </v-card>
              </div>
              <div
                style="display: flex; flex-direction: column"
                class="pt-3"
                v-else
              >
                <v-card
                  color="#f3e5f5"
                  v-for="(item, index) in PayoutObj.payment_workflow_history"
                  :key="index"
                  class="pa-5 mb-4"
                >
                  <div>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Action Taken By: </strong
                        >{{ item.action_taken_by }}</span
                      >
                    </p>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Action Time: </strong
                        >{{ item.action_time }}</span
                      >
                    </p>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Action Type: </strong
                        >{{ item.action_type }}</span
                      >
                    </p>
                    <p class="pa-0">
                      <span class="FontSize"
                        ><strong>Email ID: </strong
                        >{{ item.user_contact }}</span
                      >
                    </p>
                  </div>
                </v-card>
              </div>
            </v-tab-item>
          </v-tabs-items>
        </v-card-text>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
export default {
  props: {
    PayoutInfoDialog: Boolean,
    PayoutObj: Object,
  },

  data: () => ({
    Tabmodel: 0,
  }),

  methods: {
    viewPDFMethod(URL) {
      window.open(URL, "__blank");
    },
    PayoutInfoDialogEmit(Toggle) {
      this.$emit("clicked", Toggle);
    },
  },
};
</script>
