<template>
  <div class="ma-3">
    <v-card elevation="0">
      <Overlay :overlay="overlay" />
      <GeneratePartnerClosedReports
        :GeneratePartnerClosedReportsDialog="generatePartnerClosedReportsDialog"
        @clicked="GeneratePartnerClosedReportsDialogEmit"
      />
      <v-toolbar dense class="elevation-0">
        <div class="mr-1 ml-1 largeFontSizeNew">
          <span> Partner Closed Ticket Reports</span>
        </div>
        <v-spacer />
        <v-btn small color="primary" @click="generateReportsMethod()">
          Generate
          <v-icon small>mdi-microsoft-excel</v-icon>
        </v-btn>
        <!-- <v-btn
          small
          color="primary"
          class="mt-4"
          @click="generateNewReqReportsDialogMethod()"
        >
          Generate
          <v-icon small>mdi-microsoft-excel</v-icon>
        </v-btn> -->
      </v-toolbar>
      <!-- <v-card elevation="5" class="pa-3 mt-3">
        <div class="d-flex">
          <div style="position: relative; top: 12px">
            <v-menu
              offset-y
              ref="menum"
              v-model="menum"
              :return-value.sync="month"
              transition="scale-transition"
              :close-on-content-click="false"
            >
              <template v-slot:activator="{ on, attrs }">
                <v-text-field
                  dense
                  outlined
                  readonly
                  v-on="on"
                  v-bind="attrs"
                  v-model="month"
                  label="Select Month"
                  class="FontSize smallwidth"
                ></v-text-field>
              </template>
              <v-date-picker
                no-title
                scrollable
                type="month"
                v-model="month"
                :max="maxMonth"
              >
                <v-spacer></v-spacer>
                <v-btn text color="primary" @click="menu = false">
                  Cancel
                </v-btn>
                <v-btn text color="primary" @click="$refs.menum.save(month)">
                  OK
                </v-btn>
              </v-date-picker>
            </v-menu>
          </div>
          <div class="ms-auto" style="position: relative; top: 13px">
            <v-btn small color="primary" @click="generateReportsMethod()">
              Generate
              <v-icon small>mdi-microsoft-excel</v-icon>
            </v-btn>
          </div>
        </div>
      </v-card> -->
      <v-card elevation="5" class="pa-5 mt-3">
        <v-expansion-panels>
          <v-expansion-panel
            v-for="(report, i) in allReports"
            :key="i"
            class="mt-2 mb-2"
          >
            <v-expansion-panel-header
              class="FontSize font-weight-bold black--text"
              expand-icon="mdi-menu-down"
            >
              <div class="d-flex">
                <div>
                  {{ formattedFolderName(report) }}
                </div>
                <div class="ms-auto">
                  Generated By: {{ report.metadata.user_name }}
                </div>
              </div>
            </v-expansion-panel-header>
            <v-expansion-panel-content>
              <v-data-table
                :headers="reportsHeader"
                :items="report.files"
                hide-default-footer
                dense
                class="TableValFontsize"
              >
                <template v-slot:[`item.file_name`]="{ item }">
                  <div class="FontSize">
                    {{ formattedFileName(item) }}
                  </div>
                </template>
                <template v-slot:[`item.file_url`]="{ item }">
                  <div>
                    <v-btn
                      small
                      dense
                      color="green"
                      class="white--text"
                      @click="downloadReportMethod(item)"
                    >
                      Download
                    </v-btn>
                  </div>
                </template>
              </v-data-table>
            </v-expansion-panel-content>
          </v-expansion-panel>
        </v-expansion-panels>
      </v-card>
    </v-card>
  </div>
</template>

<script>
import Overlay from "@/components/Extras/OverlayView.vue";
import Snackbar from "@/components/Extras/SnackbarView.vue";
import { API, graphqlOperation } from "aws-amplify";
import { ShareMonthlyClosedTicketReportDetailsToPartners } from "@/graphql/mutations.js";
import { ListExcelOfSharedMonthlyClosedTicketReportDetailsToPartners } from "@/graphql/queries.js";
import GeneratePartnerClosedReports from "@/components/Analytics/Dialogs/GeneratePartnerClosedReports.vue";
export default {
  components: {
    Overlay,
    Snackbar,
    GeneratePartnerClosedReports,
  },

  data: () => ({
    menum: false,
    month: new Date().toISOString().substr(0, 7),
    maxMonth: "",
    SnackBarComponent: {},
    renderComp: true,
    overlay: false,
    formatedMonth: "",
    fromDate: null,
    toDate: null,
    allReports: [],
    reportsHeader: [
      { text: "File Name", value: "file_name" },
      { text: "Download", value: "file_url" },
    ],
    generatePartnerClosedReportsDialog: false,
  }),

  watch: {
    month(val) {
      this.getMonthAndDateDetails();
    },
  },

  async mounted() {
    this.overlay = true;
    this.maxMonth = `${new Date().getFullYear()}-${(new Date().getMonth() + 1)
      .toString()
      .padStart(2, "0")}`;
    await this.callApiMethod();
  },

  methods: {
    getMonthAndDateDetails() {
      const [year, month] = this.month.split("-");
      const date = new Date(`${year}-${month}-01`);
      const shortMonth = date.toLocaleString("en-US", { month: "short" });
      this.formatedMonth = `${shortMonth}-${year}`;
      const from = new Date(year, month - 1, 1, 0, 0, 0);
      this.fromDate = Math.floor(from.getTime() / 1000);
      const end = new Date(year, month, 0, 23, 59, 59);
      this.toDate = Math.floor(end.getTime() / 1000);
      console.log("FromDate:", this.fromDate);
      console.log("ToDate:", this.toDate);
    },
    async callApiMethod() {
      try {
        const result = await API.graphql(
          graphqlOperation(
            ListExcelOfSharedMonthlyClosedTicketReportDetailsToPartners,
            {
              input: {
                organization_id:
                  this.$store.getters.get_current_user_details.organization_id,
                user_id: this.$store.getters.get_current_user_details.user_id,
              },
            }
          )
        );
        const response = JSON.parse(
          result.data
            .ListExcelOfSharedMonthlyClosedTicketReportDetailsToPartners
        ).item;
        this.allReports = response;
        console.log("REPORTS_RESPO", response);
        this.alignPartnerReportsMethod();
      } catch (error) {
        //
      } finally {
        this.overlay = false;
      }
    },

    // // alignPartnerReportsMethod() {
    // //   this.properlyAlignedReports = this.allReports.map((item) => );
    // // },

    formattedFolderName(report) {
      if (Object.keys(report).length > 0) {
        const folderName = `${report.folder_name}-(${report.time.slice(
          0,
          10
        )})`;
        return folderName;
      }
    },

    formattedFileName(fileName) {
      const splitted = fileName.split("/");
      const getLastIndex = splitted[splitted.length - 1];
      const againSplit = getLastIndex.split(".");
      console.log("AGIN_SPLI", getLastIndex);
      return againSplit[0];
    },

    downloadReportMethod(url) {
      window.open(url, "__blank");
    },

    async generateReportsMethod() {
      this.generatePartnerClosedReportsDialog = true;
      //   try {
      //     this.getMonthAndDateDetails();
      //     const apiName = ShareMonthlyClosedTicketReportDetailsToPartners;
      //     const result = await API.graphql(
      //       graphqlOperation(apiName, {
      //         input: {
      //           organization_id:
      //             this.$store.getters.get_current_user_details.organization_id,
      //           user_id: this.$store.getters.get_current_user_details.user_id,
      //           from_date: this.fromDate,
      //           to_date: this.toDate,
      //           month: this.formatedMonth,
      //         },
      //       })
      //     );

      //     const response = JSON.parse(result.data.apiName);
      //     console.log("GENERATE_EXCEL", response);
      //   } catch (error) {
      //     console.log("Error", error);
      //   }
    },

    async GeneratePartnerClosedReportsDialogEmit(Toggle) {
      this.generatePartnerClosedReportsDialog = false;
      if (Toggle === 2) {
        await this.callApiMethod();
      }
    },
  },
};
</script>
