<template>
  <div>
    <ViewAttachments
      :previewAttachments="previewAttachments"
      :StoreArray="StoreArray"
      @clicked="previewAttachmentsEmit"
    />
    <v-dialog v-model="PurchaseOrderDetailsDialog" persistent :width="1000">
      <v-card>
        <v-toolbar dark dense class="elevation-0" color="primary">
          <div>Purchase Order Details</div>

          <v-spacer></v-spacer>
          <v-btn icon @click="PurchaseOrderDetailsDialogEmit((Toggle = 1))"
            ><v-icon>mdi-close</v-icon></v-btn
          >
        </v-toolbar>
        <div>
          <v-tabs v-model="Tabmodel" slider-color="primary">
            <v-tab class="text-capitalize">Ticket Details</v-tab>
            <v-tab
              class="text-capitalize"
              v-if="
                StoreObj.po_status === 'PAYMENT_DONE' ||
                StoreObj.po_status === 'CLOSED'
              "
              >Payment Details</v-tab
            >
          </v-tabs>
          <v-tabs-items v-model="Tabmodel">
            <v-tab-item>
              <v-card-text v-if="Tabmodel === 0">
                <div v-if="StoreObj.ticket_id || StoreObj.module_id">
                  <div
                    class="FontSize red--text text-center mt-3"
                    v-if="this.noDataText != undefined && this.noDataText != ''"
                  >
                    Error : {{ this.noDataText }}
                  </div>
                  <span class="FontSize font-weight-bold black--text"
                    >PO Generated By:
                    <!-- <span v-if="TicketDetailsList"> -->
                    <!-- <span v-if="TicketDetailsList.length != 0"> -->
                    <span class="font-weight-regular black--text"
                      >{{ StoreObj.initiater_user_name }}
                    </span>
                    <!-- </span> -->
                    <!-- </span> -->
                  </span>
                  <v-row no-gutters>
                    <div class="ml-2 mt-4 font-weight-bold black--text">
                      Customer Information :
                    </div>
                  </v-row>
                  <v-card-title>
                    <v-row no-gutters>
                      <v-col cols="12" sm="12" md="4" xs="12">
                        <span class="FontSize font-weight-bold black--text"
                          >Ticket-Id :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span
                                class="font-weight-regular black--text"
                                v-if="TicketDetailsList[0].custom_ticket_id"
                                >{{ TicketDetailsList[0].custom_ticket_id }}
                              </span>
                              <span
                                class="font-weight-regular black--text"
                                v-else
                                >{{ TicketDetailsList[0].ticket_id }}
                              </span>
                            </span>
                          </span>
                        </span>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Ticket Type :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">{{
                                TicketDetailsList[0].ticket_type
                              }}</span>
                            </span>
                          </span>
                        </div>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Ticket Status :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">{{
                                TicketDetailsList[0].ticket_status
                              }}</span>
                            </span>
                          </span>
                        </div>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Customer ID :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">{{
                                TicketDetailsList[0].customer_unique_id
                              }}</span>
                            </span>
                          </span>
                        </div>
                      </v-col>
                      <v-col cols="12" sm="12" md="4" xs="12">
                        <div class="FontSize font-weight-bold black--text">
                          Customer Name :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">
                                {{
                                  TicketDetailsList[0].customer_company_name
                                }}</span
                              >
                            </span>
                          </span>
                        </div>
                        <div class="FontSize font-weight-bold black--text">
                          Contact Person Name :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">
                                {{ TicketDetailsList[0].customer_name }}</span
                              >
                            </span>
                          </span>
                        </div>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Contact Person Email :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">
                                {{
                                  TicketDetailsList[0].customer_email_id
                                }}</span
                              >
                            </span></span
                          >
                        </div>
                      </v-col>
                      <v-col cols="12" sm="12" md="4" xs="12">
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Contact Person Phone Number :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">
                                {{
                                  TicketDetailsList[0].customer_full_number
                                }}</span
                              >
                            </span>
                          </span>
                        </div>
                        <div
                          class="FontSize font-weight-bold mt-n2 black--text"
                        >
                          Service Address :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">{{
                                TicketDetailsList[0].ticket_address
                              }}</span>
                            </span>
                          </span>
                        </div>
                        <div
                          class="FontSize font-weight-bold mt-n2 black--text"
                        >
                          Ticket Priority :
                          <span v-if="TicketDetailsList">
                            <span v-if="TicketDetailsList.length != 0">
                              <span class="font-weight-regular black--text">{{
                                TicketDetailsList[0].ticket_priority
                              }}</span>
                            </span>
                          </span>
                        </div>
                      </v-col>
                    </v-row>
                  </v-card-title>
                  <div>
                    <div class="ml-2 mt-n3 font-weight-bold black--text">
                      Service Information :
                    </div>
                    <v-card-title>
                      <v-row no-gutters>
                        <v-col cols="12" sm="12" md="4" xs="12">
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Category Name :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">{{
                                  TicketDetailsList[0].category_name
                                }}</span>
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Product Name :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">{{
                                  TicketDetailsList[0].service_name
                                }}</span>
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Serial Number :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">{{
                                  TicketDetailsList[0].service_serial_number
                                }}</span>
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Service Type:
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].service_type_name
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Support:
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].ticket_warranty_type
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Support Type:
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{ TicketDetailsList[0].support_type }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Ticket Type:
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].ticket_creation_type
                                  }}
                                </span>
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Free of Cost:
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span
                                  class="font-weight-regular green--text"
                                  v-if="
                                    TicketDetailsList[0].is_free_of_cost == true
                                  "
                                >
                                  Yes
                                </span>
                                <span
                                  class="font-weight-regular red--text"
                                  v-else
                                >
                                  No
                                </span>
                              </span>
                            </span>
                          </div>
                        </v-col>
                        <v-col cols="12" sm="12" md="4" xs="12">
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Service Partner Name :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].reporting_manager_name
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Reporting Manager :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0]
                                      .ticket_reporting_manager_name
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Primary Representative :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].representative_name
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Secondary Representative :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0]
                                      .secondary_technician_name
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Ticket Problem Description :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0]
                                      .service_ticket_description
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Ticket Invoice Date :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span
                                  class="font-weight-regular black--text"
                                  v-if="
                                    TicketDetailsList[0].ticket_warranty_details
                                  "
                                >
                                  {{
                                    TicketDetailsList[0].ticket_warranty_details
                                      .ticket_invoice_date
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div v-if="TicketDetailsList">
                            <div v-if="TicketDetailsList.length != 0">
                              <div
                                v-if="TicketDetailsList[0].installation_date"
                                class="FontSize font-weight-bold black--text mt-n2"
                              >
                                Ticket Installation Date :<span
                                  class="font-weight-regular black--text"
                                >
                                  {{
                                    TicketDetailsList[0].installation_date
                                  }}</span
                                >
                              </div>
                            </div>
                          </div>
                          <div v-if="TicketDetailsList">
                            <div v-if="TicketDetailsList.length != 0">
                              <div
                                v-if="
                                  TicketDetailsList[0].ticket_warranty_details
                                "
                                class="FontSize font-weight-bold black--text mt-n2"
                              >
                                Ticket Invoice Number :<span
                                  class="font-weight-regular black--text"
                                >
                                  {{
                                    TicketDetailsList[0].ticket_warranty_details
                                      .ticket_invoice_number
                                  }}</span
                                >
                              </div>
                            </div>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Comments :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{ TicketDetailsList[0].comments }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Ticket Closed Location :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span
                                  class="font-weight-regular black--text"
                                  v-if="
                                    TicketDetailsList[0].ticket_closed_location
                                  "
                                >
                                  {{
                                    TicketDetailsList[0].ticket_closed_location.replaceAll(
                                      "_",
                                      " "
                                    )
                                  }}
                                </span>
                              </span>
                            </span>
                          </div>
                        </v-col>
                        <v-col cols="12" sm="12" md="4" xs="12">
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Prefered Visit Date :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].prefered_visit_date
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Prefered Visit Time :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">{{
                                  TicketDetailsList[0].prefered_visit_time
                                }}</span>
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Call Received Date :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].customer_call_date
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Call Received Time :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">
                                  {{
                                    TicketDetailsList[0].customer_call_time
                                  }}</span
                                >
                              </span>
                            </span>
                          </div>

                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            WIP Sub Stage :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">{{
                                  TicketDetailsList[0].wip_sub_stage_name
                                }}</span>
                              </span>
                            </span>
                          </div>
                          <div
                            class="FontSize font-weight-bold black--text mt-n2"
                          >
                            Additional Comments :
                            <span v-if="TicketDetailsList">
                              <span v-if="TicketDetailsList.length != 0">
                                <span class="font-weight-regular black--text">{{
                                  TicketDetailsList[0].additional_comments
                                }}</span>
                              </span>
                            </span>
                          </div>
                        </v-col>
                      </v-row>
                    </v-card-title>
                  </div>
                </div>
                <div v-else class="d-flex justify-center">
                  <div class="mt-5">
                    <strong>No ticket details available!</strong>
                  </div>
                </div>
              </v-card-text>
            </v-tab-item>
            <v-tab-item>
              <v-card-text v-if="Tabmodel === 1">
                <div v-if="StoreObj.payment_details">
                  <v-card-title>
                    <v-row no-gutters>
                      <v-col cols="12" sm="12" md="4" xs="12">
                        <span class="FontSize font-weight-bold black--text"
                          >Date of Payment:

                          <span class="font-weight-regular black--text"
                            >{{
                              StoreObj.payment_details.date_of_payment || "N/A"
                            }}
                          </span>
                        </span>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Mode of Payment:
                          <span class="font-weight-regular black--text"
                            >{{
                              StoreObj.payment_details.mode_of_payment || "N/A"
                            }}
                          </span>
                        </div>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Payment Reference Number:

                          <span class="font-weight-regular black--text">{{
                            StoreObj.payment_details.payment_reference_number ||
                            "N/A"
                          }}</span>
                        </div>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Payment Type:
                          <span class="font-weight-regular black--text">{{
                            StoreObj.payment_details.payment_type || "N/A"
                          }}</span>
                        </div>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Payment Value:
                          <span class="font-weight-regular black--text">{{
                            StoreObj.payment_details.payment_value || "N/A"
                          }}</span>
                        </div>
                        <div
                          class="FontSize font-weight-bold black--text mt-n2"
                        >
                          Attachemnts:
                          <v-btn
                            icon
                            v-if="StoreObj.attachments"
                            @click="openAttachmentsDialog()"
                          >
                            <v-icon color="primary" small>mdi-paperclip</v-icon>
                          </v-btn>
                          <span v-else>N/A</span>
                        </div>
                      </v-col>
                    </v-row>
                  </v-card-title>
                </div>
                <div v-else class="d-flex justify-center">
                  <div class="mt-5">
                    <strong>No payment details available!</strong>
                  </div>
                </div>
              </v-card-text>
            </v-tab-item>
          </v-tabs-items>
        </div>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
import ViewAttachments from "@/components/FGR/Dialogs/ViewFgrAttachments.vue";
import { GetTicketDetails } from "@/mixins/Approvals/GetAllTicketDetailsByTicketId.js";

export default {
  mixins: [GetTicketDetails],
  props: { PurchaseOrderDetailsDialog: Boolean, StoreObj: Object },
  components: {
    ViewAttachments,
  },
  data: () => ({
    Tabmodel: 0,
    StoreArray: [],
    previewAttachments: false,
  }),
  watch: {
    async PurchaseOrderDetailsDialog(val) {
      if (val) {
        console.log("PO_STOREOBJ", this.StoreObj);
        this.TicketDetailsListMethod(
          this.StoreObj.module_id != undefined
            ? this.StoreObj.module_id
            : this.StoreObj.ticket_id
        );
      }
    },
  },
  methods: {
    openAttachmentsDialog() {
      this.previewAttachments = true;
      this.StoreArray = this.StoreObj.attachments;
    },

    PurchaseOrderDetailsDialogEmit(Toggle) {
      this.$emit("clicked", Toggle);
    },
    previewAttachmentsEmit(Toggle) {
      this.previewAttachments = false;
    },
  },
};
</script>
